<?php

declare(strict_types=1);

use App\Http\Controllers\Api\ActivityListController;
use App\Http\Controllers\Api\ActivityShowController;
use App\Http\Controllers\Api\AgentIdeAdapterChoicesController;
use App\Http\Controllers\Api\AgentIdeMessageController;
use App\Http\Controllers\Api\AppAgentIdeController;
use App\Http\Controllers\Api\AppListController;
use App\Http\Controllers\Api\AppPruneController;
use App\Http\Controllers\Api\AppRegisterController;
use App\Http\Controllers\Api\AppRemoveController;
use App\Http\Controllers\Api\AppRootController;
use App\Http\Controllers\Api\AppRuntimeMountController;
use App\Http\Controllers\Api\AppShowController;
use App\Http\Controllers\Api\AppStoreController;
use App\Http\Controllers\Api\AppWebSocketController;
use App\Http\Controllers\Api\AppWorkerController;
use App\Http\Controllers\Api\CaRootController;
use App\Http\Controllers\Api\CloudflareController;
use App\Http\Controllers\Api\DatabaseConnections\DatabaseConnectionAttachController;
use App\Http\Controllers\Api\DatabaseConnections\DatabaseConnectionDescribeController;
use App\Http\Controllers\Api\DatabaseConnections\DatabaseConnectionDestroyController;
use App\Http\Controllers\Api\DatabaseConnections\DatabaseConnectionDetachController;
use App\Http\Controllers\Api\DatabaseConnections\DatabaseConnectionIndexController;
use App\Http\Controllers\Api\DatabaseConnections\DatabaseConnectionQueryController;
use App\Http\Controllers\Api\DatabaseConnections\DatabaseConnectionSchemaController;
use App\Http\Controllers\Api\DatabaseConnections\DatabaseConnectionShowController;
use App\Http\Controllers\Api\DatabaseConnections\DatabaseConnectionStoreController;
use App\Http\Controllers\Api\DatabaseConnections\DatabaseConnectionTablesController;
use App\Http\Controllers\Api\DatabaseConnections\DatabaseConnectionUpdateController;
use App\Http\Controllers\Api\DeployController;
use App\Http\Controllers\Api\DoctorFixController;
use App\Http\Controllers\Api\DoctorRunController;
use App\Http\Controllers\Api\FirewallRuleDestroyController;
use App\Http\Controllers\Api\FirewallRuleListController;
use App\Http\Controllers\Api\FirewallRuleStoreController;
use App\Http\Controllers\Api\GatewayStatusController;
use App\Http\Controllers\Api\InternalExecutorTokenController;
use App\Http\Controllers\Api\MeController;
use App\Http\Controllers\Api\MetricsCredentialsController;
use App\Http\Controllers\Api\MetricsCredentialsResetController;
use App\Http\Controllers\Api\MetricsStatusController;
use App\Http\Controllers\Api\NodeAgentIdeController;
use App\Http\Controllers\Api\NodeGrantController;
use App\Http\Controllers\Api\NodeListController;
use App\Http\Controllers\Api\NodePermissionsController;
use App\Http\Controllers\Api\NodeRemoveController;
use App\Http\Controllers\Api\NodeRevokeController;
use App\Http\Controllers\Api\NodeRoleAddController;
use App\Http\Controllers\Api\NodeRoleListController;
use App\Http\Controllers\Api\NodeRoleRemoveController;
use App\Http\Controllers\Api\NodeShowController;
use App\Http\Controllers\Api\NodeStoreController;
use App\Http\Controllers\Api\NodeUpdateController;
use App\Http\Controllers\Api\OperationEventStreamController;
use App\Http\Controllers\Api\PhpRuntimeController;
use App\Http\Controllers\Api\PhpUseController;
use App\Http\Controllers\Api\ProcessDestroyController;
use App\Http\Controllers\Api\ProcessEventIngestController;
use App\Http\Controllers\Api\ProcessListController;
use App\Http\Controllers\Api\ProcessLogController;
use App\Http\Controllers\Api\ProcessRestartController;
use App\Http\Controllers\Api\ProcessStartController;
use App\Http\Controllers\Api\ProcessStopController;
use App\Http\Controllers\Api\ProcessStoreController;
use App\Http\Controllers\Api\ProcessUpdateController;
use App\Http\Controllers\Api\ProfileController;
use App\Http\Controllers\Api\ProxyRouteDestroyController;
use App\Http\Controllers\Api\ProxyRouteListController;
use App\Http\Controllers\Api\ProxyRouteStoreController;
use App\Http\Controllers\Api\S3CredentialsController;
use App\Http\Controllers\Api\S3PublishController;
use App\Http\Controllers\Api\S3UnpublishController;
use App\Http\Controllers\Api\ScheduleDestroyController;
use App\Http\Controllers\Api\ScheduleListController;
use App\Http\Controllers\Api\ScheduleLogsController;
use App\Http\Controllers\Api\ScheduleRunController;
use App\Http\Controllers\Api\ScheduleShowController;
use App\Http\Controllers\Api\ScheduleStoreController;
use App\Http\Controllers\Api\ToolCredentialsController;
use App\Http\Controllers\Api\ToolInstallController;
use App\Http\Controllers\Api\ToolListController;
use App\Http\Controllers\Api\ToolReconfigureController;
use App\Http\Controllers\Api\ToolRemoveController;
use App\Http\Controllers\Api\ToolShowController;
use App\Http\Controllers\Api\ToolUpdateBulkController;
use App\Http\Controllers\Api\ToolUpdateController;
use App\Http\Controllers\Api\UpdateAllController;
use App\Http\Controllers\Api\UpdateAllStartController;
use App\Http\Controllers\Api\VpnClientCreateController;
use App\Http\Controllers\Api\VpnClientDisableController;
use App\Http\Controllers\Api\VpnClientEnableController;
use App\Http\Controllers\Api\VpnClientListController;
use App\Http\Controllers\Api\VpnClientRemoveController;
use App\Http\Controllers\Api\VpnWebUiChangePasswordController;
use App\Http\Controllers\Api\WorkspaceHistoryController;
use App\Http\Controllers\Api\WorkspaceListController;
use App\Http\Controllers\Api\WorkspaceLogController;
use App\Http\Controllers\Api\WorkspaceRemoveController;
use App\Http\Controllers\Api\WorkspaceSetupController;
use App\Http\Controllers\Api\WorkspaceShowController;
use App\Http\Controllers\Api\WorkspaceStepDeleteController;
use App\Http\Controllers\Api\WorkspaceStepListController;
use App\Http\Controllers\Api\WorkspaceStepStoreController;
use App\Http\Controllers\Api\WorkspaceStoreController;
use App\Http\Middleware\CorrelationHeader;
use App\Http\Middleware\LogActivity;
use App\Http\Middleware\RequireGrantPermission;
use App\Http\Middleware\WireGuardIdentity;
use Illuminate\Support\Facades\Route;

Route::middleware(CorrelationHeader::class)->group(function (): void {
    Route::get('/status', GatewayStatusController::class)->name('api.status');
    Route::get('/ca/root', CaRootController::class);

    Route::middleware([WireGuardIdentity::class, RequireGrantPermission::class])->group(function (): void {
        Route::get('/operations/{operationRun}/events', OperationEventStreamController::class)
            ->name('api.operations.events');
    });

    Route::middleware([WireGuardIdentity::class, RequireGrantPermission::class, LogActivity::class])->group(function (): void {
        Route::get('/activity', ActivityListController::class);
        Route::get('/activity/{id}', ActivityShowController::class);
        Route::get('/agent-ide/adapters', AgentIdeAdapterChoicesController::class);
        Route::post('/agent-ide/message', AgentIdeMessageController::class);
        Route::get('/cloudflare/zones', [CloudflareController::class, 'zones']);
        Route::get('/cloudflare/zones/{zone}/dns', [CloudflareController::class, 'dnsRecords']);
        Route::post('/cloudflare/zones/{zone}/dns', [CloudflareController::class, 'storeDnsRecord']);
        Route::delete('/cloudflare/zones/{zone}/dns/{record}', [CloudflareController::class, 'removeDnsRecord']);
        Route::post('/cloudflare/cache/flush', [CloudflareController::class, 'flushCache']);
        Route::post('/cloudflare/cache-rules/{app}', [CloudflareController::class, 'addCacheRule']);
        Route::delete('/cloudflare/cache-rules/{app}', [CloudflareController::class, 'removeCacheRule']);
        Route::put('/cloudflare/zones/{zone}/ssl', [CloudflareController::class, 'enableSsl']);
        Route::put('/cloudflare/zones/{zone}/ssl/disable', [CloudflareController::class, 'disableSsl']);
        Route::post('/doctor/fix', DoctorFixController::class);
        Route::post('/doctor/run', DoctorRunController::class);
        Route::get('/database-connections', DatabaseConnectionIndexController::class);
        Route::post('/database-connections', DatabaseConnectionStoreController::class);
        Route::post('/database-connections/query', DatabaseConnectionQueryController::class);
        Route::get('/database-connections/tables', DatabaseConnectionTablesController::class);
        Route::get('/database-connections/schema', DatabaseConnectionSchemaController::class);
        Route::get('/database-connections/describe', DatabaseConnectionDescribeController::class);
        Route::get('/database-connections/{connection}', DatabaseConnectionShowController::class);
        Route::patch('/database-connections/{connection}', DatabaseConnectionUpdateController::class);
        Route::delete('/database-connections/{connection}', DatabaseConnectionDestroyController::class);
        Route::post('/database-connections/{connection}/targets', DatabaseConnectionAttachController::class);
        Route::delete('/database-connections/{connection}/targets', DatabaseConnectionDetachController::class);
        Route::get('/deploy/history', [DeployController::class, 'history']);
        Route::get('/deploy/log/{run}', [DeployController::class, 'log']);
        Route::post('/deploy/run', [DeployController::class, 'run']);
        Route::get('/deploy/steps', [DeployController::class, 'listSteps']);
        Route::post('/deploy/steps', [DeployController::class, 'storeStep']);
        Route::delete('/deploy/steps/{step}', [DeployController::class, 'removeStep']);
        Route::post('/internal-executor/token/verify', InternalExecutorTokenController::class);
        Route::get('/me', MeController::class);
        Route::get('/metrics/status', MetricsStatusController::class);
        Route::get('/metrics/credentials', MetricsCredentialsController::class);
        Route::post('/metrics/credentials/reset', MetricsCredentialsResetController::class);
        Route::post('/events/process', ProcessEventIngestController::class);
        Route::get('/firewall-rules', FirewallRuleListController::class);
        Route::post('/firewall-rules', FirewallRuleStoreController::class);
        Route::delete('/firewall-rules/{name}', FirewallRuleDestroyController::class);
        Route::get('/processes', ProcessListController::class);
        Route::post('/processes', ProcessStoreController::class);
        Route::post('/processes/restart', ProcessRestartController::class);
        Route::post('/processes/start', ProcessStartController::class);
        Route::post('/processes/stop', ProcessStopController::class);
        Route::get('/processes/{name}/log', ProcessLogController::class);
        Route::delete('/processes/{name}', ProcessDestroyController::class);
        Route::patch('/processes/{name}', ProcessUpdateController::class);
        Route::get('/profile/resolve', [ProfileController::class, 'resolve']);
        Route::get('/profile', ProfileController::class);
        Route::get('/php/runtime', PhpRuntimeController::class);
        Route::post('/php/use', PhpUseController::class);
        Route::get('/proxy-routes', ProxyRouteListController::class);
        Route::post('/proxy-routes', ProxyRouteStoreController::class);
        Route::delete('/proxy-routes/{domain}', ProxyRouteDestroyController::class);
        Route::get('/s3/credentials', S3CredentialsController::class);
        Route::post('/s3/public-hosts', S3PublishController::class);
        Route::delete('/s3/public-hosts/{host}', S3UnpublishController::class);
        Route::get('/schedules', ScheduleListController::class);
        Route::post('/schedules', ScheduleStoreController::class);
        Route::post('/schedules/{name}/run', ScheduleRunController::class);
        Route::get('/schedules/{name}/logs', ScheduleLogsController::class);
        Route::delete('/schedules/{name}', ScheduleDestroyController::class);
        Route::get('/schedules/{name}', ScheduleShowController::class);
        Route::get('/workspaces', WorkspaceListController::class);
        Route::post('/workspaces', WorkspaceStoreController::class);
        Route::post('/workspaces/setup', WorkspaceSetupController::class);
        Route::get('/workspaces/history/resolve-by-path', [WorkspaceHistoryController::class, 'fromPath']);
        Route::get('/workspaces/runs/{run}/log', WorkspaceLogController::class);
        Route::get('/workspaces/steps/{phase}', WorkspaceStepListController::class);
        Route::post('/workspaces/steps/{phase}', WorkspaceStepStoreController::class);
        Route::delete('/workspaces/steps/{phase}/{step}', WorkspaceStepDeleteController::class);
        Route::get('/workspaces/resolve-by-path', [WorkspaceShowController::class, 'fromPath']);
        Route::get('/workspaces/{name}/history', WorkspaceHistoryController::class);
        Route::delete('/workspaces/{name}', WorkspaceRemoveController::class);
        Route::get('/workspaces/{name}', WorkspaceShowController::class);
        Route::get('/apps', AppListController::class);
        Route::post('/apps/register', AppRegisterController::class);
        Route::post('/apps', AppStoreController::class);
        Route::post('/apps/prune', AppPruneController::class);
        Route::post('/apps/{app}/agent-ide', AppAgentIdeController::class);
        Route::post('/apps/{app}/root', AppRootController::class);
        Route::post('/apps/{app}/websocket/enable', [AppWebSocketController::class, 'enable']);
        Route::post('/apps/{app}/websocket/disable', [AppWebSocketController::class, 'disable']);
        Route::get('/apps/{app}/websocket/credentials', [AppWebSocketController::class, 'credentials']);
        Route::get('/apps/{app}/mounts', [AppRuntimeMountController::class, 'index']);
        Route::post('/apps/{app}/mounts', [AppRuntimeMountController::class, 'store']);
        Route::delete('/apps/{app}/mounts', [AppRuntimeMountController::class, 'destroy']);
        Route::get('/apps/{app}/worker', [AppWorkerController::class, 'show']);
        Route::post('/apps/{app}/worker/enable', [AppWorkerController::class, 'enable']);
        Route::post('/apps/{app}/worker/disable', [AppWorkerController::class, 'disable']);
        Route::delete('/apps/{app}', AppRemoveController::class);
        Route::get('/apps/{app}', AppShowController::class);
        Route::get('/tools', ToolListController::class);
        Route::delete('/tools/{tool}', ToolRemoveController::class);
        Route::post('/tools/{tool}/install', ToolInstallController::class);
        Route::post('/tools/update', ToolUpdateBulkController::class);
        Route::post('/tools/{tool}/update', ToolUpdateController::class);
        Route::get('/tools/{tool}/credentials', ToolCredentialsController::class);
        Route::post('/tools/{tool}/reconfigure', ToolReconfigureController::class);
        Route::get('/tools/{tool}', ToolShowController::class);
        Route::post('/update/all/start', UpdateAllStartController::class)->name('api.update.all.start');
        Route::post('/update/all', UpdateAllController::class);
        Route::get('/vpn/clients', VpnClientListController::class);
        Route::post('/vpn/clients', VpnClientCreateController::class);
        Route::post('/vpn/clients/{name}/enable', VpnClientEnableController::class);
        Route::post('/vpn/clients/{name}/disable', VpnClientDisableController::class);
        Route::delete('/vpn/clients/{name}', VpnClientRemoveController::class);
        Route::post('/vpn/web-ui/password', VpnWebUiChangePasswordController::class);
        Route::get('/nodes', NodeListController::class);
        Route::post('/nodes', NodeStoreController::class);
        Route::post('/nodes/grant', NodeGrantController::class);
        Route::post('/nodes/permissions', NodePermissionsController::class);
        Route::post('/nodes/revoke', NodeRevokeController::class);
        Route::get('/nodes/{name}/roles', NodeRoleListController::class);
        Route::post('/nodes/{name}/roles', NodeRoleAddController::class);
        Route::delete('/nodes/{name}/roles/{role}', NodeRoleRemoveController::class);
        Route::post('/nodes/{name}/agent-ide', NodeAgentIdeController::class);
        Route::delete('/nodes/{name}', NodeRemoveController::class);
        Route::put('/nodes/{name}', NodeUpdateController::class);
        Route::get('/nodes/{name}', NodeShowController::class);
    });
});
